server:
  port: 23032

spring:
  application:
    name: library-app

  datasource:
    url: ${LOCAL_DATASOURCE_URL:jdbc:postgresql://localhost:5432/library_caching}
    username: ${LOCAL_POSTGRES_USERNAME}
    password: ${LOCAL_POSTGRES_PASSWORD}

